### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by Bhupesh-V** [piccolbo/feedcache3#1]
I know the project has been unmaintained know but installing this on python gives the following error

```bash
ERROR: Command errored out with exit status 1:
     command: /home/bhupesh/Documents/defe/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3hhn18i2/feedcache/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3hhn18i2/feedcache/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3hhn18i2/feedcache/pip-egg-info
         cwd: /tmp/pip-install-3hhn18i2/feedcache/
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
    Traceback (most recent call last):
      File "/tmp/pip-install-3hhn18i2/feedcache/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3hhn18i2/feedcache/setup.py", line 31, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-install-3hhn18i2/feedcache/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-install-3hhn18i2/feedcache/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/tmp/pip-install-3hhn18i2/feedcache/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I would like this project to reborn if possible

**Comment by piccolbo** [comment]
Can't reproduce. How did you install? Please exact commands.

**Comment by Bhupesh-V** [comment]
I created a `python3` virtual environment and ran
`pip install feedcache`

**Comment by piccolbo** [comment]
You are not installing this package. This package is called feedcache3 and is not available on pypi.
